name: "FreeBSD"
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:  
  build:
    name: Build & Test
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - freebsd-latest
        version:
          - mini
        arch:
          - amd64
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Setup environment & Build Arturo
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg-update
            pkg install -y wget nim gmp mpfr bash databases/sqlite3
          run: |
            ./build.nims build --mode ${{ matrix.version }} --log
            export PATH="$HOME/.arturo/bin:$PATH"
            arturo tools/tester.art
       
      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-${{matrix.version}}-${{matrix.arch}}-freebsd"
          path: bin/arturo
